.PHONY: clean All

All:
	@echo "----------Building project:[ HW1_ExtraCredit - Debug ]----------"
	@cd "HW1_ExtraCredit" && "$(MAKE)" -f  "HW1_ExtraCredit.mk"
clean:
	@echo "----------Cleaning project:[ HW1_ExtraCredit - Debug ]----------"
	@cd "HW1_ExtraCredit" && "$(MAKE)" -f  "HW1_ExtraCredit.mk" clean
