.PHONY: clean All

All:
	@echo "----------Building project:[ HW2_Q3 - Debug ]----------"
	@cd "HW2_Q3" && "$(MAKE)" -f  "HW2_Q3.mk"
clean:
	@echo "----------Cleaning project:[ HW2_Q3 - Debug ]----------"
	@cd "HW2_Q3" && "$(MAKE)" -f  "HW2_Q3.mk" clean
